version: '{build}'

image: Visual Studio 2017

install:
 - ps: | # Set env vars for versioning
    
    
    
 - git submodule update --init --recursive
 - gen.bat

# Set target platform
platform: x64 

# Set solution configuration
configuration: Release 
 
build:
  parallel: true
  project: build-windows/CTREmulator
  verbosity: normal
  
after_build:
 - ps: | # Package artifact
    7z a -m0=LZMA2 -mx9 $env:BUILD .\build-windows\bin\Release\*
test: off

artifacts:
 - path: $(BUILD)
   name: CTREmulator

on_finish:
- ps: | # Bump AppVeyor Version

    Â© 2018 GitHub, Inc.
    Terms
    Privacy
    Security
